{% set name = "chart-studio" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a17283b62470306d77060b200f13f9749c807dd15613c113d36f8d057f5c7019

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - plotly
    - requests
    - retrying >=1.3.3
    - six

test:
  imports:
    - chart_studio

about:
  home: https://github.com/plotly/plotly.py
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: This package contains utilities for interfacing with Plotly's Chart Studio service
  doc_url: https://help.plot.ly/tutorials/#fundamentals
  dev_url: https://github.com/plotly/plotly.py/tree/master/packages/python/chart-studio

extra:
  recipe-maintainers:
    - jonmmease
    - timkpaine
    - dhirschfeld
    - nicolaskruchten
    - emmanuelle
